# Generated by Django 5.1.1 on 2024-09-24 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homescreen', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_code', models.CharField(max_length=5)),
                ('description', models.CharField(max_length=1023)),
                ('category', models.CharField(max_length=255)),
                ('prereq', models.CharField(max_length=1023)),
            ],
        ),
        migrations.CreateModel(
            name='Reviews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_code', models.CharField(max_length=5)),
                ('online', models.BooleanField()),
                ('review_text', models.CharField(max_length=1023)),
                ('interesting_rating', models.IntegerField()),
                ('easy_rating', models.IntegerField()),
                ('overall_rating', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='Member',
        ),
    ]
