# Generated by Django 5.1.1 on 2024-09-25 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homescreen', '0003_reviews_review_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='courses',
            name='course_name',
            field=models.CharField(default='Def', max_length=255),
            preserve_default=False,
        ),
    ]
