# Generated by Django 5.1.1 on 2024-10-13 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homescreen', '0006_reviews_moderated_reviews_user_ip_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='courses',
            name='deprecated',
            field=models.BooleanField(default=False),
        ),
    ]
